my_fist_site/communications/urls.py
from django.urls import path
from . import views


app_name = 'communications'

urlpatterns = [
    # path('', views.com_list),
    # path('pp/', views.communications_list),
    # path('pp/add/', views.com_list),
    # path('about', views.CVg.as_view()),
    path('', views.list_coom, name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
         views.post_detail, name='post_detail'),
    path('<int:post_id>/share/',
         views.post_share, name='post_share'),
]

my_fist_site/my_fist_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('communications.urls'))
]
  

my_fist_site/communications/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


class Post(models.Model):
    Status_choices = (('draft', 'Draft'), ('published', 'published'))
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,
                              choices=Status_choices,
                              default='draft')

    def get_absolute_url(self):
        return reverse('communications:post_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day,
                             self.slug]
                       )

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title


class Comments(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Комментарий оставлен {self.name} в статье {self.post}'
# Create your models here.

my_fist_site/communications/forms.py
from django import forms
from .models import Comments


class EmailPostFrom(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.CharField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ('name', 'email', 'body')

my_fist_site/communications/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.views import View

from .models import Post
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import EmailPostFrom, CommentForm


# Create your views here.

def list_coom(request):
    objects_list = Post.objects.all()
    paginator = Paginator(objects_list, 2)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request, 'commu/list.html', {'posts': posts, 'page': page})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, status='published',
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)
    comments = post.comments.filter(active=True)

    new_comments = None

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comments = comment_form.save(commit=False)
            new_comments.post = post
            new_comments.save()


    else:
        comment_form = CommentForm()

    return render(request, 'commu/detail.html',
                  {'post': post,
                   'comments': comments,
                   'new_comments': new_comments,
                   'comment_form': comment_form})


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    if request.method == 'POST':
        form = EmailPostFrom(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f'{cd["name"]} рекомендоманвал к прочению {post.title}'
            massage = f'прочтите {post.title} по адресу {post_url}\n\n' \
                      f'{cd["name"]} коментарии : {cd["comments"]}'
            # sendemail
            sent = True

    else:
        form = EmailPostFrom
    return render(request, 'commu/share.html', {'post': post, 'form': form, 'sent': sent})

# def communications_list(request, *args, **kwargs):
#     return render(request, 'commu/commun_ht.html', {})
#
#
# def com_list(request, *args, **kwargs):
#     return render(request, 'commu/content.html', {})
#
#
# class CVg(View):
#     def get(self, request):
#         return render(request, 'commu/register.html')

my_fist_site/communications/templates/commu/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="{% static "css/commu.css" %}" rel = "stylecheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
    <div id="sidebar">
        <h2>my blog</h2>
        <p>this is my blog</p>
    </div>
</body>
</html>

my_fist_site/communications/templates/commu/commun_ht.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <ul>
        <li><a href="add/">
            как
        </a>
        </li>
        <li>
            твои
        </li>
        <li>
            дела
        </li>
    </ul>
</head>
<body>

</body>
</html>

my_fist_site/communications/templates/commu/content.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <ul>
        <li>
            <a href="/">
                что
            </a>
        </li>
        <li>
            ты
        </li>
        <li>
            делаешь
        </li>
    </ul>
</head>
<body>

</body>
</html>

my_fist_site/communications/templates/commu/detail.html
{% extends 'commu/base.html' %}
{% block title %} {{ post.title}} {% endblock %}

{% block content %}
    <h1>{{ post.title}}</h1>
        <p class="date">
            Published {{ post.publish }} by {{ post.author }}
        </p>
    {{ post.body|linebreaks}}
    <p>
        <a class="btn btn-primary" href='{% url "communications:post_share" post.id%}'>кнопка</a>
    </p>
 {% with comments.count as total_comments %}
    <h2>
        {{ total_comments }} комментариев {{ total_comments }}
    </h2>
 {% endwith %}
    {% for comment in comments %}
    <div class ='comment'>
        <p class ='info'>
            комментарий №{{ forloop.counter }} оставлен {{ comment.name }}
            {{ comment.created }}
        </p>
        {{ comment.body|linebreaks }}
    </div>
    {% empty %}
    <p>
        нету статей
    </p>
    {% endfor %}
    {% if new_comment %}
        <h2>ваш комментарий добавлен</h2>
    {% else %}
        <h2>добавить новый комментарий</h2>
        <form method="post">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <p><input type="submit">добавить комментарий </p>
        </form>
    {% endif %}
{% endblock %}

my_fist_site/communications/templates/commu/list.html
{% extends 'commu/base.html' %}
{% block title %} fist site {% endblock %}

{% block content %}
    <h1>my blog</h1>
    {% for post in posts %}
    <h2>
        <a href="{{ post.get_absolute_url }}">
            {{ post.title }}
        </a>
    </h2>
    <p class="date">
        Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|truncatewords:30|linebreaks}}
    {% endfor %}
    {% include "commu/pagination.html" with page=posts %}
{% endblock %}

my_fist_site/communications/templates/commu/pagination.html
<div class="pagination">
    <samp class="step-link">
        {% if page.has_previous %}
            <a href="?page= {{ page.previous_page_number }}">Пердыдущая</a>
        {% endif %}
        <span class="current">
            страница {{ page.number }} из {{ page.paginator.num_pages }}
        </span>
        {% if page.has_next %}
            <a href="?page= {{ page.next_page_number }}">следующая</a>
        {% endif %}
    </samp>
</div>

my_fist_site/communications/templates/commu/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
        <ul>
        <li>
            <a href="/">
                что
            </a>
        </li>
        <li>
            ты
        </li>
        <li>
            делаешь
        </li>
    </ul>
</head>
<body>

</body>
</html>

my_fist_site/communications/templates/commu/share.html
{% extends 'commu/base.html' %}
{% block title %}поделиться статьей {% endblock %}

{% block content %}
    {% if sent %}
        <h1>сообщение успешно отправлено</h1>
        <p>
            {{ post.title}} было успешно отправлено в адрес {{ form.cleaned_date.to}}
        </p>
    {% else %}
        <h1>поделиться статьей '{{ post.title }}'</h1>
        <form method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="отправить">
        </form>
    {% endif %}
{% endblock %}